### ISSUE TITLE
Final testing of tracker

### ISSUE THREAD

**Issue by ghost** [GSoft-Goldsmiths/iLost-Back-end#6]
- [x] Drop test

- [x] Battery life test

- [x] Usability test

- [x] Indoor location accuracy 

- [x] Outdoor location accuracy

We know the location accuracy won't be good but we still need some figures to add to a final spec-sheet of our product. Of course, we can't do maximum altitude or temperature test.

**Comment by ghost** [comment]
Project is over
